### ISSUE TITLE
Image are not displayed when the image name contains a white space

### ISSUE THREAD

**Issue by F-A** [ShadowKyogre/mikidown#74] opened 2016-05-18 21:05 UTC
When adding an image to a notebook whose name contains a white space, the picture will not be displayed.
However, the user can correct this behaviour manually by editing the notebook markdown and replacing the white space with %20 in the image path.

**Comment by ShadowKyogre** [comment] 2016-05-19 19:31
Reproduced it with an **image** name that has spaces. Not just a notebook name with spaces. I'll see what's going on in the source code.

**Comment by ShadowKyogre** [comment] 2016-05-19 19:35
Minimal test case reproduction in python 3.5:
~~~~~
Python 3.5.1 (default, Mar  3 2016, 09:29:07) 
[GCC 5.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import markdown
>>> markdown.
...Extension             ...blockparser           ...markdownFromFile
...Markdown              ...blockprocessors       ...odict
...__all__               ...build_block_parser    ...postprocessors
...__builtins__          ...build_inlinepatterns  ...preprocessors
...__cached__            ...build_postprocessors  ...serializers
...__doc__               ...build_preprocessors   ...sys
...__file__              ...build_treeprocessors  ...to_html_string
...__loader__            ...codecs                ...to_xhtml_string
...__name__              ...extensions            ...treeprocessors
...__package__           ...importlib             ...unicode_literals
...__path__              ...inlinepatterns        ...util
...__spec__              ...logger                ...version
...__version__           ...logging               ...version_info
...absolute_import       ...markdown              ...warnings
>>> markdown.markdown('![file with spaces](../attachments/Changelog/file with spaces.png)')
('<p><img alt="file with spaces" src="../attachments/Changelog/file" '
 'title="with spaces.png" /></p>')
>>> 
~~~~~

That's the reproduced html. Let me take a look at the markdown specification to see if this is expected behavior from a compliant parser.

**Comment by ShadowKyogre** [comment] 2016-05-19 19:37
Yup, this is expected behavior. See <http://daringfireball.net/projects/markdown/syntax#img>

That being said, what would you recommend to improve this since it might not be something most people know?

**Comment by ShadowKyogre** [comment] 2016-05-19 19:48
Pushed a fix in the develop branch and tested it. Let me know if it works for you too.

**Comment by F-A** [comment] 2016-05-19 21:16
Thanks for the fast answer and fix!

This is actually what I would have expected: parsing the path to the image directly at the import.

However, the fix works only partially: It work if you import the picture using the shortcut or the top menu but not if you just drag&drop the image. In this case, the same code need to be added in the insertFromMimeData function (l.139)

**Comment by ShadowKyogre** [comment] 2016-05-19 22:15
Oooh, okay. I knew I must've missed something. Give me one moment! Am multi-tasking atm.

**Comment by F-A** [comment] 2016-05-20 07:18
No problem, there is no hurry. I just wanted to notify the bug. :)

I can do a pull request otherwise. But I'm also pretty busy at the moment,
so it might take some time.

2016-05-20 0:46 GMT+02:00 ShadowKyogre <notifications@github.com>:

**Comment by ShadowKyogre** [comment] 2016-05-20 14:21
Pushed another commit yesterday to address case you mentioned. It should work completely dandy now.

On May 20, 2016, F-A <notifications@github.com> wrote:
>No problem, there is no hurry. I just wanted to notify the bug. :)
>
>I can do a pull request otherwise. But I'm also pretty busy at the
>moment,
>so it might take some time.
>
>2016-05-20 0:46 GMT+02:00 ShadowKyogre <notifications@github.com>:
>
>> Oooh, okay. I knew I must've missed something. Give me one moment! Am
>> multi-tasking atm.
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly or view it on GitHub
>>
><https://github.com/ShadowKyogre/mikidown/issues/74#issuecomment-220467380>
>>
>
>
>---
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/ShadowKyogre/mikidown/issues/74#issuecomment-220535065

-- 
Sent with <a href="https://play.google.com/store/apps/details?id=com.onegravity.k10.pro2"><b>K-@ Mail</b></a> - the evolution of emailing.

**Closed** 2016-07-06 00:50 UTC
